var BubbleGame;
var bubbleGame = {};
bubbleGame.addHandler = function(callback) {};
bubbleGame.addPlayer = function(playerName) {};
bubbleGame.setScore = function(playerName, n) {};
bubbleGame.setOrder = function(playerName, n) {};
bubbleGame.setStat = function(statName, n) {};
bubbleGame.addBubble = function() {};
bubbleGame.removeBubble = function() {};
bubbleGame.destroy = function() {};