{:config {:order 0, :description "End of Game", :name :endgame}
 :data
 [
  [:node-create [] :map]
  [:node-create [:login] :map]
  [:node-create [:login :name] :map]
  [:transform-enable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :wait}]]
  :break
  [:value [:login :name] nil "Peter"]
  :break
  [:value [:login :name] "Peter" nil]
  [:transform-disable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :wait}]]
  [:node-destroy [:login :name] :map]
  [:node-destroy [:login] :map]
  [:node-create [:wait] :map]
  [:node-create [:wait :start] :map]
  [:transform-enable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-create [:wait :counters] :map]
  [:node-create [:wait :counters "Peter"] :map]
  :break
  [:node-create [:wait :counters "abc"] :map]
  [:value [:wait :counters "abc"] nil 0]
  :break
  [:node-create [:wait :counters "xyz"] :map]
  [:value [:wait :counters "xyz"] nil 0]
  :break
  [:value [:wait :counters "abc"] 0 1]
  :break
  [:value [:wait :counters "xyz"] 0 1]
  :break
  [:transform-disable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-destroy [:wait :start] :map]
  [:node-destroy [:wait :counters "Peter"] :map]
  [:value [:wait :counters "abc"] 1 nil]
  [:node-destroy [:wait :counters "abc"] :map]
  [:value [:wait :counters "xyz"] 1 nil]
  [:node-destroy [:wait :counters "xyz"] :map]
  [:node-destroy [:wait :counters] :map]
  [:node-destroy [:wait] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 2]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 0.67]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 1]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 1]
  [:node-create [:main :counters "Peter"] :map]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 1]
  [:node-create [:main :add-bubbles] :map]
  [:value [:main :add-bubbles] nil {:clock 9, :count 3}]
  [:node-create [:main :remove-bubbles] :map]
  [:value [:main :remove-bubbles] nil {:total 2}]
  [:node-create [:main :player-order] :map]
  [:node-create [:main :player-order "xyz"] :map]
  [:value [:main :player-order "xyz"] nil 0]
  [:node-create [:main :player-order "abc"] :map]
  [:value [:main :player-order "abc"] nil 1]
  [:node-create [:main :player-order "Peter"] :map]
  [:value [:main :player-order "Peter"] nil 2]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 40]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 20]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 15]
  :break
  [:value [:main :add-bubbles] {:clock 9, :count 3} {:clock 10, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 20 9]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  :break
  [:value [:main :total-count] 2 3]
  [:value [:main :average-count] 0.67 1]
  [:value [:main :max-count] 1 2]
  [:value [:main :counters "abc"] 1 2]
  [:value [:main :remove-bubbles] {:total 2} {:total 3}]
  [:value [:main :player-order "abc"] 1 0]
  [:value [:main :player-order "xyz"] 0 1]
  [:value [:pedestal :debug :dataflow-time] 9 20]
  [:value [:pedestal :debug :dataflow-time-avg] 14 15]
  :break
  [:value [:main :add-bubbles] {:clock 10, :count 3} {:clock 11, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 20 7]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  :break
  [:value [:main :total-count] 3 4]
  [:value [:main :average-count] 1 1.33]
  [:value [:main :max-count] 2 3]
  [:value [:main :counters "abc"] 2 3]
  [:value [:main :remove-bubbles] {:total 3} {:total 4}]
  [:value [:pedestal :debug :dataflow-time] 7 17]
  :break
  [:value [:main :add-bubbles] {:clock 11, :count 3} {:clock 12, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 17 8]
  :break
  [:value [:main :total-count] 4 5]
  [:value [:main :average-count] 1.33 1.67]
  [:value [:main :counters "xyz"] 1 2]
  [:value [:main :remove-bubbles] {:total 4} {:total 5}]
  [:value [:pedestal :debug :dataflow-time] 8 17]
  :break
  [:value [:main :total-count] 5 6]
  [:value [:main :average-count] 1.67 2]
  [:value [:main :max-count] 3 4]
  [:value [:main :counters "abc"] 3 4]
  [:value [:main :remove-bubbles] {:total 5} {:total 6}]
  [:value [:pedestal :debug :dataflow-time] 17 18]
  :break
  [:value [:main :add-bubbles] {:clock 12, :count 3} {:clock 13, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 18 7]
  :break
  [:value [:main :total-count] 6 296]
  [:value [:main :average-count] 2 98.67]
  [:value [:main :max-count] 4 290]
  [:value [:main :counters "Peter"] nil 290]
  [:value [:main :player-order "Peter"] 2 0]
  [:value [:main :player-order "abc"] 0 1]
  [:value [:main :player-order "xyz"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 7 14]
  :break
  [:value [:main :total-count] 296 297]
  [:value [:main :average-count] 98.67 99]
  [:value [:main :counters "abc"] 4 5]
  [:value [:main :remove-bubbles] {:total 6} {:total 7}]
  [:value [:pedestal :debug :dataflow-time] 14 15]
  :break
  [:value [:main :add-bubbles] {:clock 13, :count 3} {:clock 14, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 15 6]
  :break
  [:value [:main :total-count] 297 298]
  [:value [:main :average-count] 99 99.33]
  [:value [:main :counters "xyz"] 2 3]
  [:value [:main :remove-bubbles] {:total 7} {:total 8}]
  [:value [:pedestal :debug :dataflow-time] 6 16]
  :break
  [:value [:main :total-count] 298 299]
  [:value [:main :average-count] 99.33 99.67]
  [:value [:main :counters "abc"] 5 6]
  [:value [:main :remove-bubbles] {:total 8} {:total 9}]
  [:value [:pedestal :debug :dataflow-time] 16 17]
  :break
  [:value [:main :add-bubbles] {:clock 14, :count 3} {:clock 15, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 17 6]
  [:value [:pedestal :debug :dataflow-time-avg] 14 13]
  :break
  [:value [:main :total-count] 299 300]
  [:value [:main :average-count] 99.67 100]
  [:value [:main :counters "abc"] 6 7]
  [:value [:main :remove-bubbles] {:total 9} {:total 10}]
  [:value [:pedestal :debug :dataflow-time] 6 38]
  [:value [:pedestal :debug :dataflow-time-avg] 13 14]
  :break
  [:value [:main :total-count] 300 10]
  [:value [:main :average-count] 100 3.33]
  [:value [:main :counters "Peter"] 290 0]
  [:value [:main :player-order "abc"] 1 0]
  [:value [:main :player-order "xyz"] 2 1]
  [:value [:main :player-order "Peter"] 0 2]
  [:value [:pedestal :debug :dataflow-time] 38 19]
  :break
  [:value [:main :max-count] 290 0]
  [:value [:pedestal :debug :dataflow-time] 19 4]
  :break
  [:value [:main :total-count] 10 3]
  [:value [:main :average-count] 3.33 1]
  [:value [:main :max-count] 0 3]
  [:value [:main :counters "abc"] 7 0]
  [:value [:main :remove-bubbles] {:total 10} {:total 3}]
  [:value [:main :player-order "xyz"] 1 0]
  [:value [:main :player-order "Peter"] 2 1]
  [:value [:main :player-order "abc"] 0 2]
  [:value [:pedestal :debug :dataflow-time] 4 22]
  :break
  [:value [:pedestal :debug :dataflow-time] 22 3]
  :break
  [:value [:main :total-count] 3 0]
  [:value [:main :average-count] 1 0]
  [:value [:main :counters "xyz"] 3 0]
  [:value [:main :remove-bubbles] {:total 3} {:total 0}]
  [:value [:pedestal :debug :dataflow-time] 3 14]
  :break
  [:transform-disable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-destroy [:main :my-counter] :map]
  [:value [:main :total-count] 0 nil]
  [:node-destroy [:main :total-count] :map]
  [:value [:main :average-count] 0 nil]
  [:node-destroy [:main :average-count] :map]
  [:value [:main :max-count] 3 nil]
  [:node-destroy [:main :max-count] :map]
  [:value [:main :counters "abc"] 0 nil]
  [:node-destroy [:main :counters "abc"] :map]
  [:value [:main :counters "Peter"] 0 nil]
  [:node-destroy [:main :counters "Peter"] :map]
  [:value [:main :counters "xyz"] 0 nil]
  [:node-destroy [:main :counters "xyz"] :map]
  [:node-destroy [:main :counters] :map]
  [:value [:main :add-bubbles] {:clock 15, :count 3} nil]
  [:node-destroy [:main :add-bubbles] :map]
  [:value [:main :remove-bubbles] {:total 0} nil]
  [:node-destroy [:main :remove-bubbles] :map]
  [:value [:main :player-order "xyz"] 0 nil]
  [:node-destroy [:main :player-order "xyz"] :map]
  [:value [:main :player-order "abc"] 2 nil]
  [:node-destroy [:main :player-order "abc"] :map]
  [:value [:main :player-order "Peter"] 1 nil]
  [:node-destroy [:main :player-order "Peter"] :map]
  [:node-destroy [:main :player-order] :map]
  [:node-destroy [:main] :map]
  [:value [:pedestal :debug :dataflow-time-max] 40 nil]
  [:node-destroy [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time] 14 nil]
  [:node-destroy [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time-avg] 14 nil]
  [:node-destroy [:pedestal :debug :dataflow-time-avg] :map]
  [:node-destroy [:pedestal :debug] :map]
  [:node-destroy [:pedestal] :map]
  [:node-create [:wait] :map]
  [:node-create [:wait :start] :map]
  [:transform-enable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-create [:wait :counters] :map]
  [:node-create [:wait :counters "abc"] :map]
  [:value [:wait :counters "abc"] nil 0]
  [:node-create [:wait :counters "Peter"] :map]
  [:value [:wait :counters "Peter"] nil 0]
  [:node-create [:wait :counters "xyz"] :map]
  [:value [:wait :counters "xyz"] nil 0]
  [:node-create [:wait :winner] :map]
  [:value [:wait :winner] nil {:player "Peter", :score 290}]
  [:node-create [:wait :high-scores] :map]
  [:value [:wait :high-scores] nil ({:player "Peter", :score 290})]
  :break
  [:value [:wait :counters "abc"] 0 8]
  :break
  [:value [:wait :counters "xyz"] 0 4]
  :break
  [:value [:wait :counters "abc"] 8 9]
  :break
  [:value [:wait :counters "xyz"] 4 5]
  :break
  [:transform-disable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-destroy [:wait :start] :map]
  [:value [:wait :counters "abc"] 9 nil]
  [:node-destroy [:wait :counters "abc"] :map]
  [:value [:wait :counters "Peter"] 0 nil]
  [:node-destroy [:wait :counters "Peter"] :map]
  [:value [:wait :counters "xyz"] 5 nil]
  [:node-destroy [:wait :counters "xyz"] :map]
  [:node-destroy [:wait :counters] :map]
  [:value [:wait :winner] {:player "Peter", :score 290} nil]
  [:node-destroy [:wait :winner] :map]
  [:value [:wait :high-scores] ({:player "Peter", :score 290}) nil]
  [:node-destroy [:wait :high-scores] :map]
  [:node-destroy [:wait] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 14]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 4.67]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 9]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 9]
  [:node-create [:main :counters "Peter"] :map]
  [:value [:main :counters "Peter"] nil 0]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 5]
  [:node-create [:main :add-bubbles] :map]
  [:value [:main :add-bubbles] nil {:clock 17, :count 3}]
  [:node-create [:main :remove-bubbles] :map]
  [:value [:main :remove-bubbles] nil {:total 14}]
  [:node-create [:main :player-order] :map]
  [:node-create [:main :player-order "abc"] :map]
  [:value [:main :player-order "abc"] nil 0]
  [:node-create [:main :player-order "xyz"] :map]
  [:value [:main :player-order "xyz"] nil 1]
  [:node-create [:main :player-order "Peter"] :map]
  [:value [:main :player-order "Peter"] nil 2]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 40]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 16]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 13]
  :break
  [:value [:main :total-count] 14 15]
  [:value [:main :average-count] 4.67 5]
  [:value [:main :max-count] 9 10]
  [:value [:main :counters "abc"] 9 10]
  [:value [:main :remove-bubbles] {:total 14} {:total 15}]
  [:value [:pedestal :debug :dataflow-time] 16 11]
  :break
  [:value [:main :add-bubbles] {:clock 17, :count 3} {:clock 18, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 11 16]
  :break
  [:value [:main :total-count] 15 16]
  [:value [:main :average-count] 5 5.33]
  [:value [:main :max-count] 10 11]
  [:value [:main :counters "abc"] 10 11]
  [:value [:main :remove-bubbles] {:total 15} {:total 16}]
  [:value [:pedestal :debug :dataflow-time] 16 32]
  [:value [:pedestal :debug :dataflow-time-avg] 13 14]
  :break
  [:value [:main :total-count] 16 17]
  [:value [:main :average-count] 5.33 5.67]
  [:value [:main :max-count] 11 12]
  [:value [:main :counters "abc"] 11 12]
  [:value [:main :remove-bubbles] {:total 16} {:total 17}]
  [:value [:pedestal :debug :dataflow-time-max] 40 60]
  [:value [:pedestal :debug :dataflow-time] 32 60]
  [:value [:pedestal :debug :dataflow-time-avg] 14 15]
  :break
  [:value [:main :add-bubbles] {:clock 18, :count 3} {:clock 19, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 60 6]
  :break
  [:value [:main :total-count] 17 18]
  [:value [:main :average-count] 5.67 6]
  [:value [:main :max-count] 12 13]
  [:value [:main :counters "abc"] 12 13]
  [:value [:main :remove-bubbles] {:total 17} {:total 18}]
  [:value [:pedestal :debug :dataflow-time] 6 13]
  :break
  [:value [:main :total-count] 18 19]
  [:value [:main :average-count] 6 6.33]
  [:value [:main :counters "xyz"] 5 6]
  [:value [:main :remove-bubbles] {:total 18} {:total 19}]
  [:value [:pedestal :debug :dataflow-time] 13 15]
  :break
  [:value [:main :total-count] 19 20]
  [:value [:main :average-count] 6.33 6.67]
  [:value [:main :max-count] 13 14]
  [:value [:main :counters "abc"] 13 14]
  [:value [:main :remove-bubbles] {:total 19} {:total 20}]
  :break
  [:value [:main :total-count] 20 520]
  [:value [:main :average-count] 6.67 173.33]
  [:value [:main :max-count] 14 500]
  [:value [:main :counters "Peter"] 0 500]
  [:value [:main :player-order "Peter"] 2 0]
  [:value [:main :player-order "abc"] 0 1]
  [:value [:main :player-order "xyz"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 15 57]
  :break
  [:value [:main :total-count] 520 20]
  [:value [:main :average-count] 173.33 6.67]
  [:value [:main :counters "Peter"] 500 0]
  [:value [:main :player-order "abc"] 1 0]
  [:value [:main :player-order "xyz"] 2 1]
  [:value [:main :player-order "Peter"] 0 2]
  [:value [:pedestal :debug :dataflow-time] 57 16]
  :break
  [:value [:main :max-count] 500 0]
  [:value [:pedestal :debug :dataflow-time] 16 3]
  :break
  [:value [:main :total-count] 20 6]
  [:value [:main :average-count] 6.67 2]
  [:value [:main :max-count] 0 6]
  [:value [:main :counters "abc"] 14 0]
  [:value [:main :remove-bubbles] {:total 20} {:total 6}]
  [:value [:main :player-order "xyz"] 1 0]
  [:value [:main :player-order "Peter"] 2 1]
  [:value [:main :player-order "abc"] 0 2]
  [:value [:pedestal :debug :dataflow-time] 3 22]
  :break
  [:value [:pedestal :debug :dataflow-time] 22 0]
  :break
  [:value [:main :total-count] 6 0]
  [:value [:main :average-count] 2 0]
  [:value [:main :counters "xyz"] 6 0]
  [:value [:main :remove-bubbles] {:total 6} {:total 0}]
  [:value [:pedestal :debug :dataflow-time] 0 16]
  :break
  [:transform-disable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-destroy [:main :my-counter] :map]
  [:value [:main :total-count] 0 nil]
  [:node-destroy [:main :total-count] :map]
  [:value [:main :average-count] 0 nil]
  [:node-destroy [:main :average-count] :map]
  [:value [:main :max-count] 6 nil]
  [:node-destroy [:main :max-count] :map]
  [:value [:main :counters "abc"] 0 nil]
  [:node-destroy [:main :counters "abc"] :map]
  [:value [:main :counters "Peter"] 0 nil]
  [:node-destroy [:main :counters "Peter"] :map]
  [:value [:main :counters "xyz"] 0 nil]
  [:node-destroy [:main :counters "xyz"] :map]
  [:node-destroy [:main :counters] :map]
  [:value [:main :add-bubbles] {:clock 19, :count 3} nil]
  [:node-destroy [:main :add-bubbles] :map]
  [:value [:main :remove-bubbles] {:total 0} nil]
  [:node-destroy [:main :remove-bubbles] :map]
  [:value [:main :player-order "abc"] 2 nil]
  [:node-destroy [:main :player-order "abc"] :map]
  [:value [:main :player-order "xyz"] 0 nil]
  [:node-destroy [:main :player-order "xyz"] :map]
  [:value [:main :player-order "Peter"] 1 nil]
  [:node-destroy [:main :player-order "Peter"] :map]
  [:node-destroy [:main :player-order] :map]
  [:node-destroy [:main] :map]
  [:value [:pedestal :debug :dataflow-time-max] 60 nil]
  [:node-destroy [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time] 16 nil]
  [:node-destroy [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time-avg] 15 nil]
  [:node-destroy [:pedestal :debug :dataflow-time-avg] :map]
  [:node-destroy [:pedestal :debug] :map]
  [:node-destroy [:pedestal] :map]
  [:node-create [:wait] :map]
  [:node-create [:wait :start] :map]
  [:transform-enable [:wait :start] :start-game [{:io.pedestal.app.messages/topic :io.pedestal.app.messages/output, :payload {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}} {:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:active-game], :value true}]]
  [:node-create [:wait :counters] :map]
  [:node-create [:wait :counters "abc"] :map]
  [:value [:wait :counters "abc"] nil 0]
  [:node-create [:wait :counters "Peter"] :map]
  [:value [:wait :counters "Peter"] nil 0]
  [:node-create [:wait :counters "xyz"] :map]
  [:value [:wait :counters "xyz"] nil 0]
  [:node-create [:wait :winner] :map]
  [:value [:wait :winner] nil {:player "Peter", :score 500}]
  [:node-create [:wait :high-scores] :map]
  [:value [:wait :high-scores] nil ({:player "Peter", :score 500} {:player "Peter", :score 290})]
  :break
  [:value [:wait :counters "xyz"] 0 7]
  :break
  [:value [:wait :counters "abc"] 0 15]
  :break
  [:value [:wait :counters "abc"] 15 16]
 ]}