{:config {:order 0, :description "Tutorial Part 2", :name :tutorial_part2}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 2]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 0.67]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 1]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 1]
  [:node-create [:main :counters "Me"] :map]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 1]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 18]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 8]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 13]
  :break
  [:value [:main :total-count] 2 3]
  [:value [:main :average-count] 0.67 1]
  [:value [:main :max-count] 1 2]
  [:value [:main :counters "abc"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 8 12]
  [:value [:pedestal :debug :dataflow-time-avg] 13 12]
  :break
  [:value [:main :total-count] 3 4]
  [:value [:main :average-count] 1 1.33]
  [:value [:main :counters "Me"] nil 1]
  [:value [:pedestal :debug :dataflow-time] 12 11]
  :break
  [:value [:main :total-count] 4 5]
  [:value [:main :average-count] 1.33 1.67]
  [:value [:main :counters "Me"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 11 7]
  [:value [:pedestal :debug :dataflow-time-avg] 12 11]
  :break
  [:value [:main :total-count] 5 6]
  [:value [:main :average-count] 1.67 2]
  [:value [:main :max-count] 2 3]
  [:value [:main :counters "abc"] 2 3]
  [:value [:pedestal :debug :dataflow-time] 7 11]
  :break
  [:value [:main :total-count] 6 7]
  [:value [:main :average-count] 2 2.33]
  [:value [:main :counters "Me"] 2 3]
  [:value [:pedestal :debug :dataflow-time] 11 7]
  [:value [:pedestal :debug :dataflow-time-avg] 11 10]
  :break
  [:value [:main :total-count] 7 8]
  [:value [:main :average-count] 2.33 2.67]
  [:value [:main :counters "xyz"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 7 9]
  :break
  [:value [:main :total-count] 8 9]
  [:value [:main :average-count] 2.67 3]
  [:value [:main :max-count] 3 4]
  [:value [:main :counters "Me"] 3 4]
  [:value [:pedestal :debug :dataflow-time] 9 17]
  [:value [:pedestal :debug :dataflow-time-avg] 10 11]
  :break
  [:value [:main :total-count] 9 10]
  [:value [:main :average-count] 3 3.33]
  [:value [:main :max-count] 4 5]
  [:value [:main :counters "Me"] 4 5]
  :break
  [:value [:main :total-count] 10 11]
  [:value [:main :average-count] 3.33 3.67]
  [:value [:main :counters "abc"] 3 4]
  [:value [:pedestal :debug :dataflow-time] 17 16]
  :break
  [:value [:main :total-count] 11 12]
  [:value [:main :average-count] 3.67 4]
  [:value [:main :max-count] 5 6]
  [:value [:main :counters "Me"] 5 6]
  [:value [:pedestal :debug :dataflow-time-max] 18 27]
  [:value [:pedestal :debug :dataflow-time] 16 27]
  [:value [:pedestal :debug :dataflow-time-avg] 11 13]
 ]}