{:config {:order 0, :description "Recording, including Login", :name :with_login}
 :data
 [
  [:node-create [] :map]
  [:node-create [:login] :map]
  [:node-create [:login :name] :map]
  [:transform-enable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :game}]]
  :break
  [:value [:login :name] nil "Peter"]
  :break
  [:value [:login :name] "Peter" nil]
  [:transform-disable [:login :name] :login [{:io.pedestal.app.messages/type :swap, :io.pedestal.app.messages/topic [:login :name], :io.pedestal.app.messages.param/value {}} {:io.pedestal.app.messages/type :set-focus, :io.pedestal.app.messages/topic :io.pedestal.app.messages/app-model, :name :game}]]
  [:node-destroy [:login :name] :map]
  [:node-destroy [:login] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:transform-enable [:main :my-counter] :add-points [{:io.pedestal.app.messages/topic [:my-counter], :io.pedestal.app.messages.param/points {}}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 6]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 2]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 4]
  [:node-create [:main :add-bubbles] :map]
  [:value [:main :add-bubbles] nil {:clock 4, :count 3}]
  [:node-create [:main :counters] :map]
  [:node-create [:main :counters "abc"] :map]
  [:value [:main :counters "abc"] nil 4]
  [:node-create [:main :counters "Peter"] :map]
  [:node-create [:main :counters "xyz"] :map]
  [:value [:main :counters "xyz"] nil 2]
  [:node-create [:main :player-order] :map]
  [:node-create [:main :player-order "abc"] :map]
  [:value [:main :player-order "abc"] nil 0]
  [:node-create [:main :player-order "xyz"] :map]
  [:value [:main :player-order "xyz"] nil 1]
  [:node-create [:main :player-order "Peter"] :map]
  [:value [:main :player-order "Peter"] nil 2]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 52]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 12]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 18]
  :break
  [:value [:main :add-bubbles] {:clock 4, :count 3} {:clock 5, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 12 5]
  [:value [:pedestal :debug :dataflow-time-avg] 18 17]
  :break
  [:value [:main :total-count] 6 7]
  [:value [:main :average-count] 2 2.33]
  [:value [:main :max-count] 4 5]
  [:value [:main :counters "abc"] 4 5]
  [:value [:pedestal :debug :dataflow-time] 5 9]
  [:value [:pedestal :debug :dataflow-time-avg] 17 16]
  :break
  [:value [:main :total-count] 7 8]
  [:value [:main :average-count] 2.33 2.67]
  [:value [:main :counters "xyz"] 2 3]
  [:value [:pedestal :debug :dataflow-time] 9 11]
  [:value [:pedestal :debug :dataflow-time-avg] 16 15]
  :break
  [:value [:main :add-bubbles] {:clock 5, :count 3} {:clock 6, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 11 4]
  :break
  [:value [:main :total-count] 8 9]
  [:value [:main :average-count] 2.67 3]
  [:value [:main :max-count] 5 6]
  [:value [:main :counters "abc"] 5 6]
  [:value [:pedestal :debug :dataflow-time] 4 12]
  [:value [:pedestal :debug :dataflow-time-avg] 15 14]
  :break
  [:value [:main :add-bubbles] {:clock 6, :count 3} {:clock 7, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 12 7]
  :break
  [:value [:main :total-count] 9 10]
  [:value [:main :average-count] 3 3.33]
  [:value [:main :max-count] 6 7]
  [:value [:main :counters "abc"] 6 7]
  [:value [:pedestal :debug :dataflow-time] 7 12]
  :break
  [:value [:main :total-count] 10 14]
  [:value [:main :average-count] 3.33 4.67]
  [:value [:main :counters "Peter"] nil 4]
  [:value [:main :player-order "Peter"] 2 1]
  [:value [:main :player-order "xyz"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 12 10]
  :break
  [:value [:main :add-bubbles] {:clock 7, :count 3} {:clock 8, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 10 6]
  [:value [:pedestal :debug :dataflow-time-avg] 14 13]
  :break
  [:value [:main :total-count] 14 15]
  [:value [:main :average-count] 4.67 5]
  [:value [:main :max-count] 7 8]
  [:value [:main :counters "abc"] 7 8]
  [:value [:pedestal :debug :dataflow-time] 6 12]
  :break
  [:value [:main :total-count] 15 16]
  [:value [:main :average-count] 5 5.33]
  [:value [:main :counters "xyz"] 3 4]
  [:value [:main :player-order "xyz"] 2 1]
  [:value [:main :player-order "Peter"] 1 2]
  [:value [:pedestal :debug :dataflow-time] 12 13]
  :break
  [:value [:main :add-bubbles] {:clock 8, :count 3} {:clock 9, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 13 4]
  :break
  [:value [:main :total-count] 16 17]
  [:value [:main :average-count] 5.33 5.67]
  [:value [:main :max-count] 8 9]
  [:value [:main :counters "abc"] 8 9]
  [:value [:pedestal :debug :dataflow-time] 4 12]
  :break
  [:value [:main :add-bubbles] {:clock 9, :count 3} {:clock 10, :count 3}]
  [:value [:pedestal :debug :dataflow-time] 12 3]
  [:value [:pedestal :debug :dataflow-time-avg] 13 12]
  :break
  [:value [:main :total-count] 17 18]
  [:value [:main :average-count] 5.67 6]
  [:value [:main :max-count] 9 10]
  [:value [:main :counters "abc"] 9 10]
  [:value [:pedestal :debug :dataflow-time] 3 12]
 ]}